name: Deploy to Render
on:
 push:
   branches:
     - main
     
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: JorgeLNJunior/render-deploy@v1.4.3
       with:
         service_id: ${{ secrets.SERVICE_ID }}
         api_key: ${{ secrets.API_KEY }}
         clear_cache: false
         wait_deploy: false
         github_deployment: false
         deployment_environment: 'production'
         github_token: ${{ secrets.ACCESS_TOKEN }}